version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: task_manager_db
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - task_manager_network

volumes:
  mysql_data:

networks:
  task_manager_network:
